basePath: /
definitions:
  models.Song:
    properties:
      group:
        minLength: 1
        type: string
      id:
        type: integer
      link:
        type: string
      releaseDate:
        type: string
      song:
        minLength: 1
        type: string
      text:
        type: string
    required:
    - group
    - song
    type: object
  tools.Error:
    properties:
      error:
        type: string
    type: object
  tools.OK:
    properties:
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for managing music library
  title: Music Library API
  version: "1.0"
paths:
  /api/v1/songs:
    delete:
      consumes:
      - application/json
      description: delete song from library
      operationId: delete-song
      parameters:
      - description: song id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.OK'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tools.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.Error'
      summary: Delete song
      tags:
      - delete
    get:
      consumes:
      - application/json
      description: 'get song from library with filters (eq:, neq:, lt:, gt:), eq:
        for default'
      operationId: get-song
      parameters:
      - description: song id
        in: query
        name: id
        type: integer
      - description: song title
        in: query
        name: song
        type: string
      - description: song group
        in: query
        name: music_group
        type: string
      - description: song link
        in: query
        name: link
        type: string
      - description: song text
        in: query
        name: text
        type: string
      - description: song created at
        in: query
        name: release_date
        type: string
      - description: page of the data
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tools.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.Error'
      summary: Get song with filter
      tags:
      - get
    patch:
      consumes:
      - application/json
      description: edit song at library
      operationId: edit-song
      parameters:
      - description: song info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Song'
      - description: song id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.OK'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tools.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.Error'
      summary: Edit song
      tags:
      - edit
    post:
      consumes:
      - application/json
      description: add song to library
      operationId: add-song
      parameters:
      - description: song info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.OK'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tools.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.Error'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/tools.Error'
      summary: Add song
      tags:
      - add
  /api/v1/songs/{id}/text:
    get:
      consumes:
      - application/json
      description: get verse text of song from the library
      operationId: getText-song
      parameters:
      - description: verse pagination
        in: query
        name: verse
        required: true
        type: integer
      - description: song id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tools.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.Error'
      summary: Get verse text of song
      tags:
      - get
swagger: "2.0"
